from typing import Protocol, AsyncIterator
from pathlib import Path


class FileStorage(Protocol):
    async def save(self, key: str, data: bytes) -> None: ...
    async def stream(self, key: str, chunk_size: int = 8192) -> AsyncIterator[bytes]: ...
    async def exists(self, key: str) -> bool: ...
    async def size(self, key: str) -> int: ...
    async def delete_prefix(self, prefix: str) -> None: ...
    def local_path(self, key: str) -> Path: ...
